### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by Dhanachandra** [Legal-NLP-EkStep/rhetorical-role-baseline#3]
I am trying to do inference with dev.json using this line. 
`python infer_new.py  dev.json output.json model.pt`
But I encounter the above error. 
I script I used is availabe [here](https://colab.research.google.com/drive/1x41KAqXlUcqaxt9BvtAFjXesfVtgVxEF?usp=sharing)

**Comment by prathameshk** [comment]
It is a runtime warning and not an error. You can ignore them.
