### ISSUE TITLE
Runtime warning when using data around 60 cases on running inference

### ISSUE THREAD

**Issue by Akshunya1101** [Legal-NLP-EkStep/rhetorical-role-baseline#5]
```
RuntimeWarning: invalid value encountered in true_divide
  confusion = np.around(confusion_abs.astype('float') / confusion_abs.sum(axis=1)[:, np.newaxis] * 100, 2)
Traceback (most recent call last):
  File "/content/drive/MyDrive/project_folder/rhetorical-role-baseline/infer_new.py", line 108, in <module>
    pred_id=predictions['doc_names'].index(id)
ValueError: '14' is not in list
```

I am getting this error while running inference on a dataset of 60 cases. I didn't get this error on 30 cases but getting on 60. Also I looked on the input data and this id (14) is present in the data so why am I facing this issue.

**Comment by prathameshk** [comment]
This is just a warning and not an error. It would have generated the output.

**Comment by Akshunya1101** [comment]
No, please look at the last line of the error which says '14' not in list. Also the execution gets terminated so there was no output.
I added a continue in the loop whereever the specific value was not present in the keys and the output for that case didn't had any labels. Why is it the case that when output is produces, some cases are not present in the output.

**Comment by prathameshk** [comment]
There could be multiple reasons behind this. Can you find out for which particular document this is failing?

**Comment by prathameshk** [comment]
Please use opennyai library for doing all the inferencing. https://github.com/OpenNyAI/Opennyai
