### ISSUE TITLE
Test Macro score

### ISSUE THREAD

**Issue by Crestina2001** [Legal-NLP-EkStep/rhetorical-role-baseline#6]
Hello. In the description, you said that the test macro-F1 is 77.7 in the hidden test data. But when I use the dev data as the test data(cuz I don't have test data), the macro-F1 is 0.59. Are you sure it is the macro-F1 not weighted-F1 to be 77.7?

fold: 0,  epoch: 9, train duration: 119.674569606781, dev weighted-f1: 0.7934235807724592, test weighted-F1: 0.7934235807724592, test macro-F1: 0.5969997259500193, test accuracy: 0.8051406738450851

**Comment by prathameshk** [comment]
This was a mistake in the readme file. I have fixed it. The paper shows correct metric http://www.lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.470.pdf.

The test data is now available. https://huggingface.co/datasets/opennyaiorg/InRhetoricalRoles
